Page({
  data: {
   banner:[
      {
        imgsrc:"/images/banner1.jpg",
        navurl:"",
      },
      {
        imgsrc:"/images/banner1.jpg",
        navurl:"",
      },
      {
        imgsrc:"/images/banner1.jpg",
        navurl:"",
      }
    ],
    navlist:[
      {
        url:"/pages/component/informw/inform/inform",
        src:"/images/navli1.png",
        tit:"养生资讯",
      },
      {
        url:"/pages/component/healthgoods/product/product",
        src:"/images/navli2.png",
        tit:"养生产品",
      },
      {
        url:"/pages/component/brand/brand/brand",
        src:"/images/navli3.png",
        tit:"品牌汇",
      },
      {
        url:"/pages/component/liferoom/yst/yst",
        src:"/images/navli4.png",
        tit:"养生堂",
      },
      {
        url:"/pages/component/shopc/scart/scart",
        src:"/images/navli5.png",
        tit:"购物车",
      }
    ],
    everydayBuy:[
      {
        tit:"— 新品上线 —",
        url:"",
        tips:"更多养生产品推荐",
        img:["/images/daydaybuy1.jpg","/images/daydaybuy2.jpg"]
      },
      {
        tit:"— 生活养生 —",
        url:"",
        tips:"养生周边低价购",
        img:["/images/daydaybuy3.jpg","/images/daydaybuy4.jpg"]
      },
      {
        tit:"闪购",
        url:"",
        tips:"限时特卖",
        img:["/images/daydaybuy5.jpg"]
      },
      {
        tit:"养生茶",
        url:"",
        tips:"不负好时光",
        img:["/images/daydaybuy6.jpg"]
      },
      {
        tit:"滋补",
        url:"",
        tips:"守护家人健康",
        img:["/images/daydaybuy7.jpg"]
      },
      {
        tit:"健康",
        url:"",
        tips:"健康营养",
        img:["/images/daydaybuy8.jpg"]
      }
    ],
    todayRecom:[
      {
        url:"",
        src:"/images/allimg.jpg",
        tit:"养生茶"
      },
      {
        url:"",
        src:"/images/allimg.jpg",
        tit:"养生茶"
      },
      {
        url:"",
        src:"/images/allimg.jpg",
        tit:"养生茶"
      },
      {
        url:"",
        src:"/images/allimg.jpg",
        tit:"养生茶"
      }
    ],
    informtit:{
        imgbg:"/images/bgimg1.png",
        ico:"/images/zxico.png",
        tit:"每天值得观看的养生资讯",
        tips:[
          {
            ti:"养生快讯",
            url:""
          },
          {
            ti:"养生市场",
            url:""
          },
          {
            ti:"养生国际",
            url:""
          }
        ]
      },
    brandtit:{
      imgbg:"/images/bgimg2.png",
      ico:"/images/brandico.png",
      tit:"每天推荐的养生品牌",
      tips:[
        {
          ti:"克祖堂",
          url:""
        },
        {
          ti:"归灵芝",
          url:""
        },
        {
          ti:"老白金",
          url:""
        }
      ]
    },
    healthtit:{
      imgbg:"/images/bgimg3.png",
      ico:"/images/ysico.png",
      tit:"每天了解一点养生知识",
      tips:[
        {
          ti:"四季养生",
          url:""
        },
        {
          ti:"人群养生",
          url:""
        },
        {
          ti:"饮食养生",
          url:""
        }
      ]
    },
    inform:[
      {
        tit:"注意了！这个季节打喷嚏流鼻涕，可能不是感冒！",
        ys:"养生常识",
        zan:"120",
        date:"11月12日",
        url:"",
        imgsrc:"/images/allimg1.jpg"
      },
      {
        tit:"注意了！这个季节打喷嚏流鼻涕，可能不是感冒！",
        ys:"养生常识",
        zan:"120",
        date:"11月12日",
        url:"",
        imgsrc:"/images/allimg1.jpg"
      },
      {
        tit:"注意了！这个季节打喷嚏流鼻涕，可能不是感冒！",
        ys:"养生常识",
        zan:"120",
        date:"11月12日",
        url:"",
        imgsrc:"/images/allimg1.jpg"
      }
    ],
   brand:[
     {
       url:"",
       imgsrc:"/images/allimg1.jpg",
       tit:"可祖堂健康有限公司",
       txt:"可祖堂成立于1998年，是人们绿色养生，健康生活的首选",
       zan:"120",
       date:"11月12日"
      },
      {
       url:"",
       imgsrc:"/images/allimg1.jpg",
       tit:"可祖堂健康有限公司",
       txt:"可祖堂成立于1998年，是人们绿色养生，健康生活的首选",
       zan:"120",
       date:"11月12日"
      },
      {
       url:"",
       imgsrc:"/images/allimg1.jpg",
       tit:"可祖堂健康有限公司",
       txt:"可祖堂成立于1998年，是人们绿色养生，健康生活的首选",
       zan:"120",
       date:"11月12日"
      },
      {
       url:"",
       imgsrc:"/images/allimg1.jpg",
       tit:"可祖堂健康有限公司",
       txt:"可祖堂成立于1998年，是人们绿色养生，健康生活的首选",
       zan:"120",
       date:"11月12日"
     }
    ],
    health:[
      {
        url:"",
        imgsrc:"/images/banner1.jpg",
        tit:"这八大顶级食物是营养冠军！每个人都吃得起！",
        txt:"你知道吗？在食物当中有这八大食物是属于营养冠军级别，补充营养事半功倍!快来看看！",
        tips:"养生常识",
        zan:"120",
        date:"11月12日"
      },
      {
        url:"",
        imgsrc:"/images/banner1.jpg",
        tit:"这八大顶级食物是营养冠军！每个人都吃得起！",
        txt:"你知道吗？在食物当中有这八大食物是属于营养冠军级别，补充营养事半功倍!快来看看！",
        tips:"养生常识",
        zan:"120",
        date:"11月12日"
      }
    ],
    recom:[
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      }
    ]
  },
  onLoad() {
    // this.getUserInfo();
  },
  getUserInfo() {
    return new Promise((resolve, reject) => {
      if (this.userInfo) resolve(this.userInfo);

      my.getAuthCode({
        scopes: ['auth_user'],
        success: (authcode) => {
          console.info(authcode);

          my.getAuthUserInfo({
            success: (res) => {
              this.userInfo = res;
              resolve(this.userInfo);
            },
            fail: () => {
              reject({});
            },
          });
        },
        fail: () => {
          reject({});
        },
      });
    });
  },
});
