Page({
  data: {
    goodlist:[
      {
        img:"/images/allimg.jpg",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        date:"2018-05-12",
        url:""
      },
      {
        img:"/images/allimg.jpg",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        date:"2018-05-12",
        url:""
      },
      {
        img:"/images/allimg.jpg",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        date:"2018-05-12",
        url:""
      },
      {
        img:"/images/allimg.jpg",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        date:"2018-05-12",
        url:""
      },
      {
        img:"/images/allimg.jpg",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        date:"2018-05-12",
        url:""
      }
    ]
  },
  onLoad() {},
});
