Page({
  data: {
    tabArr:{
      cur:0
    },
    obligation:[
      {
        storetit:"阿尼玛",
        url:"/pages/component/myorder/ordetail/ordetail?id=0",
        list:[
          {
            gimg:"/images/allimg.jpg",
            gtit:"梦幻梦幻三部曲套装那是护肤梦幻梦幻三部曲套装那是护肤梦幻梦幻三部曲",
            ypri:"37.00",
            xpri:"25.90",
            num:"1"
          },
          {
            gimg:"/images/allimg.jpg",
            gtit:"梦幻梦幻三部曲套装那是护肤梦幻梦幻三部曲套装那是护肤梦幻梦幻三部曲",
            ypri:"37.00",
            xpri:"25.90",
            num:"1"
          }
        ]
      },
      {
        storetit:"SK-II",
        url:"/pages/component/myorder/ordetail/ordetail?id=0",
        list:[
          {
            gimg:"/images/allimg.jpg",
            gtit:"梦幻梦幻三部曲套装那是护肤梦幻梦幻三部曲套装那是护肤梦幻梦幻三部曲",
            ypri:"37.00",
            xpri:"25.90",
            num:"1"
          }
        ]
      }
    ],
    paid:[
      {
        storetit:"香奈儿",
        total:"85.00",
        url:"/pages/component/myorder/ordetail/ordetail?id=1",
        list:[
          {
            gimg:"/images/allimg.jpg",
            gtit:"梦幻梦幻三部曲套装那是护肤梦幻梦幻三部曲套装那是护肤梦幻梦幻三部曲",
            ypri:"37.00",
            xpri:"25.90",
            num:"1"
          }
        ]
      }
    ],
    wait:[
      {
        storetit:"前男友",
        total:"85.00",
        url:"/pages/component/myorder/ordetail/ordetail?id=2",
        list:[
          {
            gimg:"/images/allimg.jpg",
            gtit:"梦幻梦幻三部曲套装那是护肤梦幻梦幻三部曲套装那是护肤梦幻梦幻三部曲",
            ypri:"37.00",
            xpri:"25.90",
            num:"1"
          }
        ]
      }
    ],
    rating:[
     {
        storetit:"钢铁侠",
        total:"85.00",
        url:"/pages/component/myorder/ordetail/ordetail?id=3",
        list:[
          {
            gimg:"/images/allimg.jpg",
            gtit:"梦幻梦幻三部曲套装那是护肤梦幻梦幻三部曲套装那是护肤梦幻梦幻三部曲",
            ypri:"37.00",
            xpri:"25.90",
            num:"1"
          }
        ]
      }
    ],
    recom:[
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      }
    ]
  },
  onLoad(e) {
    let oid = parseInt(e.id);
    let tabArr = this.data.tabArr;
    tabArr.cur = oid;
    this.setData({
      tabArr:tabArr
    })
  },
  // 切换tab
  changetab(e){
    let idx = parseInt(e.currentTarget.dataset.index);
    let tabArr = this.data.tabArr;
    tabArr.cur = idx;
    this.setData({
      tabArr:tabArr
    })
  }
});
