Page({
  data: {
    tabArr:{cur:0},
    health:[
      {
        url:"",
        imgsrc:"/images/banner1.jpg",
        tit:"这八大顶级食物是营养冠军！每个人都吃得起！",
        txt:"你知道吗？在食物当中有这八大食物是属于营养冠军级别，补充营养事半功倍!快来看看！",
        tips:"养生常识",
        zan:"120",
        date:"11月12日"
      },
      {
        url:"",
        imgsrc:"/images/banner1.jpg",
        tit:"这八大顶级食物是营养冠军！每个人都吃得起！",
        txt:"你知道吗？在食物当中有这八大食物是属于营养冠军级别，补充营养事半功倍!快来看看！",
        tips:"养生常识",
        zan:"120",
        date:"11月12日"
      },
      {
        url:"",
        imgsrc:"/images/banner1.jpg",
        tit:"这八大顶级食物是营养冠军！每个人都吃得起！",
        txt:"你知道吗？在食物当中有这八大食物是属于营养冠军级别，补充营养事半功倍!快来看看！",
        tips:"养生常识",
        zan:"120",
        date:"11月12日"
      },
      {
        url:"",
        imgsrc:"/images/banner1.jpg",
        tit:"这八大顶级食物是营养冠军！每个人都吃得起！",
        txt:"你知道吗？在食物当中有这八大食物是属于营养冠军级别，补充营养事半功倍!快来看看！",
        tips:"养生常识",
        zan:"120",
        date:"11月12日"
      },
      {
        url:"",
        imgsrc:"/images/banner1.jpg",
        tit:"这八大顶级食物是营养冠军！每个人都吃得起！",
        txt:"你知道吗？在食物当中有这八大食物是属于营养冠军级别，补充营养事半功倍!快来看看！",
        tips:"养生常识",
        zan:"120",
        date:"11月12日"
      },
      {
        url:"",
        imgsrc:"/images/banner1.jpg",
        tit:"这八大顶级食物是营养冠军！每个人都吃得起！",
        txt:"你知道吗？在食物当中有这八大食物是属于营养冠军级别，补充营养事半功倍!快来看看！",
        tips:"养生常识",
        zan:"120",
        date:"11月12日"
      }
    ]
  },
  onLoad() {},
  /***tab切换***/
  tabChange(e){
    let idx = e.target.dataset.index;
    this.setData({
      "tabArr.cur":idx
    })
  }
});
