Page({
  data: {
    navaid:[
      {
        url:"/pages/component/healthgoods/goodslist/goodslist",
        imgsrc:"/images/progoodsnav1.png",
        tit:"养生茶"
      },
      {
        url:"",
        imgsrc:"/images/progoodsnav2.png",
        tit:"滋补品"
      },
      {
        url:"",
        imgsrc:"/images/progoodsnav3.png",
        tit:"健康产品"
      },
      {
        url:"",
        imgsrc:"/images/progoodsnav4.png",
        tit:"养生周边"
      }
    ],
    boutique:[
      {
        imgsrc:"/images/allimg.jpg",
        tit:"瑞典进口ICA麦片",
        price:"8.80",
        url:""
      },
      {
        imgsrc:"/images/allimg.jpg",
        tit:"瑞典进口ICA麦片",
        price:"8.80",
        url:""
      },
      {
        imgsrc:"/images/allimg.jpg",
        tit:"瑞典进口ICA麦片",
        price:"8.80",
        url:""
      }
    ],
    recom:[
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      },
      {
        imgsrc:"/images/allimg.jpg",
        url:"",
        tit:"瑞典进口ICA麦片50%水果坚果燕麦片",
        price:"8.80"
      }
    ]
  },
  onLoad() {},
});
